# Generated by Django 5.2.17 on 2026-09-24 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_ibge', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='código IBGE')),
                ('nome', models.CharField(max_length=120)),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('regiao', models.CharField(blank=True, max_length=20, verbose_name='região')),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['uf', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('co_entidade', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='código INEP')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('rede', models.CharField(choices=[('estadual', 'Estadual'), ('municipal', 'Municipal'), ('federal', 'Federal'), ('privada', 'Privada')], db_index=True, max_length=12)),
                ('localizacao', models.CharField(blank=True, choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=8, verbose_name='localização')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='painel.municipio', verbose_name='município')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ['uf', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('taxa_aprovacao', models.FloatField(blank=True, null=True, verbose_name='taxa de aprovação')),
                ('taxa_reprovacao', models.FloatField(blank=True, null=True, verbose_name='taxa de reprovação')),
                ('taxa_abandono', models.FloatField(blank=True, null=True, verbose_name='taxa de abandono')),
                ('distorcao_idade_serie', models.FloatField(blank=True, null=True, verbose_name='distorção idade-série')),
                ('inse', models.FloatField(blank=True, null=True, verbose_name='INSE')),
                ('origem', models.CharField(choices=[('INEP', 'Dados oficiais do INEP'), ('AMOSTRA', 'Amostra de desenvolvimento (não usar em resultado)')], db_index=True, default='INEP', max_length=8)),
                ('carregado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='painel.escola')),
            ],
            options={
                'verbose_name': 'indicador anual',
                'verbose_name_plural': 'indicadores anuais',
                'ordering': ['-ano', 'escola__nome'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'ano'), name='indicador_unico_por_escola_e_ano')],
            },
        ),
        migrations.CreateModel(
            name='IndiceRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('score', models.FloatField()),
                ('classe', models.CharField(choices=[('baixo', 'Risco baixo'), ('medio', 'Risco médio'), ('alto', 'Risco alto')], db_index=True, max_length=6)),
                ('versao', models.CharField(db_index=True, max_length=40)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='painel.escola')),
            ],
            options={
                'verbose_name': 'índice de risco',
                'verbose_name_plural': 'índices de risco',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'ano', 'versao'), name='risco_unico_por_escola_ano_versao')],
            },
        ),
    ]
